export const REQUEST_CUSTOMER = 'REQUEST_CUSTOMER';
export const REQUEST_CUSTOMER_DATA_ERROR = 'REQUEST_CUSTOMER_DATA_ERROR';
export const REQUEST_CUSTOMER_DATA_RECEIVED = 'REQUEST_CUSTOMER_DATA_RECEIVED';
export const REQUEST_SET_TERM = 'REQUEST_SET_TERM';
